site_name: PSMotd
site_url: http://heyitsgilbert.github.io/PSMotd
site_description: A Message of the Day (MOTD) for your PowerShell profile
repo_url: http://github.com/HeyItsGilbert/PSMotd
repo_name: HeyItsGilbert/PSMotd

theme:
  logo: assets/images/icon.png
  name: material
  features:
    - content.code.copy
    - navigation.sections
    - navigation.expand
    - navigation.top
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Changelog: "https://github.com/HeyItsGilbert/PSMotd/blob/main/CHANGELOG.md"
  - Commands:
      - en-US/

plugins:
  - search
  - include_dir_to_nav

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - toc:
      permalink: true
