name: Publish Module
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install and cache PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@2f5abdff92794d7f761f7da36f7ff295a0ec07f6 # v4.5
        with:
          modules-to-cache: BuildHelpers
      - shell: pwsh
        id: check_if_versions_bumped
        run: |
          [version]$GalleryVersion = Get-NextNugetPackageVersion -Name PSMotd -ErrorAction Stop
          [version]$GithubVersion = Get-MetaData -Path ./PSMotd/PSMotd.psd1 -PropertyName ModuleVersion -ErrorAction Stop
          $bumped = $GithubVersion -ge $GalleryVersion
          "version_bumped=$bumped" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
      - name: Publish to PSGallery
        shell: pwsh
        if: steps.check_if_versions_bumped.outputs.version_bumped == 'True'
        env:
          PSGALLERY_API_KEY: ${{ secrets.PS_GALLERY_KEY }}
        run: ./build.ps1 -Task Publish -Bootstrap
